export const skillTags = [
  { value: "developer", label: "Developer", color: "blue.500" },
  { value: "fullstack", label: "Fullstack", color: "green.400" },
  { value: "frontend", label: "Frontend", color: "orange.300" },
  { value: "backend", label: "Backend", color: "red.600" },
  { value: "solidity", label: "Solidity", color: "gray.400" },
  { value: "figma", label: "Figma", color: "purple.500" },
  { value: "ui-ux-design", label: "UI/UX Design", color: "pink.400" },
  { value: "data-science", label: "Data Science", color: "indigo.300" },
  { value: "machine-learning", label: "Machine Learning", color: "yellow.500" },
  { value: "cybersecurity", label: "Cybersecurity", color: "teal.400" },
  { value: "blockchain", label: "Blockchain", color: "cyan.700" },
  { value: "devops", label: "DevOps", color: "red.500" },
  { value: "cloud-computing", label: "Cloud Computing", color: "blue.300" },
  {
    value: "mobile-development",
    label: "Mobile Development",
    color: "orange.500",
  },
  { value: "graphic-design", label: "Graphic Design", color: "purple.600" },
  { value: "seo", label: "SEO", color: "cyan.500" },
  { value: "digital-marketing", label: "Digital Marketing", color: "red.400" },
  {
    value: "product-management",
    label: "Product Management",
    color: "red.700",
  },
  {
    value: "project-management",
    label: "Project Management",
    color: "yellow.600",
  },
  { value: "content-writing", label: "Content Writing", color: "blue.200" },
  { value: "business-analysis", label: "Business Analysis", color: "gray.600" },
  {
    value: "database-management",
    label: "Database Management",
    color: "purple.400",
  },
  {
    value: "artificial-intelligence",
    label: "Artificial Intelligence",
    color: "yellow.400",
  },
  { value: "virtual-reality", label: "Virtual Reality", color: "green.500" },
  { value: "augmented-reality", label: "Augmented Reality", color: "lime.300" },
  { value: "e-commerce", label: "E-Commerce", color: "pink.500" },
  { value: "software-testing", label: "Software Testing", color: "brown.400" },
  { value: "game-development", label: "Game Development", color: "indigo.500" },
  { value: "ethical-hacking", label: "Ethical Hacking", color: "red.800" },
  { value: "data-analysis", label: "Data Analysis", color: "purple.300" },
  { value: "big-data", label: "Big Data", color: "green.600" },
  { value: "it-support", label: "IT Support", color: "cyan.400" },
  {
    value: "network-administration",
    label: "Network Administration",
    color: "blue.600",
  },
  {
    value: "system-administration",
    label: "System Administration",
    color: "yellow.700",
  },
  { value: "video-editing", label: "Video Editing", color: "green.700" },
  { value: "motion-graphics", label: "Motion Graphics", color: "orange.600" },
  { value: "photography", label: "Photography", color: "purple.700" },
  { value: "illustration", label: "Illustration", color: "red.300" },
  { value: "animation", label: "Animation", color: "yellow.300" },
  { value: "copywriting", label: "Copywriting", color: "blue.400" },
  {
    value: "social-media-management",
    label: "Social Media Management",
    color: "red.500",
  },
  { value: "customer-support", label: "Customer Support", color: "gray.500" },
  { value: "hr-management", label: "HR Management", color: "green.400" },
  {
    value: "supply-chain-management",
    label: "Supply Chain Management",
    color: "green.300",
  },
  {
    value: "financial-analysis",
    label: "Financial Analysis",
    color: "cyan.600",
  },
  { value: "accounting", label: "Accounting", color: "yellow.800" },
  { value: "legal-compliance", label: "Legal Compliance", color: "brown.700" },
  { value: "sales", label: "Sales", color: "red.400" },
  { value: "public-relations", label: "Public Relations", color: "pink.600" },
  { value: "consulting", label: "Consulting", color: "teal.500" },
  // Added tags for web and mobile development
  { value: "html-css", label: "HTML/CSS", color: "orange.600" },
  { value: "javascript", label: "JavaScript", color: "yellow.500" },
  { value: "typescript", label: "TypeScript", color: "blue.400" },
  { value: "react", label: "React", color: "cyan.500" },
  { value: "nodejs", label: "Node.js", color: "green.500" },
  { value: "express", label: "Express.js", color: "blue.600" },
  { value: "nextjs", label: "Next.js", color: "purple.600" },
  { value: "vuejs", label: "Vue.js", color: "green.300" },
  { value: "flutter", label: "Flutter", color: "blue.700" },
  { value: "react-native", label: "React Native", color: "purple.700" },
  { value: "angular", label: "Angular", color: "red.500" },
  { value: "swift", label: "Swift", color: "pink.600" },
  { value: "kotlin", label: "Kotlin", color: "blue.900" },
  { value: "ionic", label: "Ionic", color: "green.600" },
  { value: "graphql", label: "GraphQL", color: "purple.500" },
  { value: "redux", label: "Redux", color: "cyan.400" },
  { value: "mongodb", label: "MongoDB", color: "green.400" },
  { value: "firebase", label: "Firebase", color: "orange.400" },
  { value: "docker", label: "Docker", color: "blue.800" },
  { value: "typescript", label: "TypeScript", color: "yellow.700" },
  { value: "pwa", label: "PWA", color: "teal.600" },
  { value: "websockets", label: "WebSockets", color: "red.600" },
  { value: "serverless", label: "Serverless", color: "purple.400" },
  { value: "api", label: "API", color: "green.200" },
];

export const getSkillTagDetails = (tagValue: string) => {
  const tag = skillTags.find((t) => t.value === tagValue);
  return tag || { value: tagValue, label: tagValue, color: "gray.500" };
};
